shcpms/config/routes.rb
Rails.application.routes.draw do
  get 'about' => 'pages#about', as: 'about'

  get 'index' => 'welcome#index'
   
  get 'patientspage' => 'patients#patientspage', as: 'patientspage'
  
  get 'welcome/index'
  
  #resources :patients
  
  root 'welcome#index', as: 'home'
  
  #resources :patients

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

shcpms/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

shcpms/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

shcpms/app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@title = 'About Us';
		@content = 'This service aims to unify the understanding doctors and hospitals have of their patients, creating
		a central of medical information';
	end
	
	def patientspage
		@title = 'Patients';
		@content = 'This service aims to unify the understanding doctors and hospitals have of their patients, creating
		a central of medical information';
	end
end

shcpms/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
	def patientspage
		@title = 'Patients';
		@content = 'This service aims to unify the understanding doctors and hospitals have of their patients, creating
		a central of medical information';
	end
	
end

shcpms/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
	@title = 'Welcome';
	@content = 'This is the Health Service Executives software for use by professionals in the medical health industry in
	the	Republic of Irelands.'  
	end
end

shcpms/app/helpers/application_helper.rb
module ApplicationHelper
end

shcpms/app/helpers/doctors_helper.rb
module DoctorsHelper
end

shcpms/app/helpers/pages_helper.rb
module PagesHelper
end

shcpms/app/helpers/patients_helper.rb
module PatientsHelper
end

shcpms/app/helpers/welcome_helper.rb
module WelcomeHelper
end

shcpms/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shcpms</title>
    <%= csrf_meta_tags %>
	<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>	
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<script src="http://code.jquery.com/jquery-latest.min.js"></script> <script src="js/bootstrap.min.js"></script>

  </head>

  <body>
	<div>
	<%= image_tag "banner.png", alt: "banner_pic", class: "img-responsive", style:"width: 100%; height: 150px"%>
	</div>


	
<nav class="navbar navbar-inverse">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
        </button>
	
		<div class="collapse navbar-collapse" id="myNavbar"> 
			<ul class="nav navbar-nav">
			<li><%= link_to "I.M.H.", about_path %></li>
			  <li><%= link_to "Home", home_path %></li>
			  <li><%= link_to "About", about_path %></li>
			  <li><%= link_to "Patients", patientspage_path %></li>
			</ul>
		</div>
	</div>
</nav>
	
 
    <%= yield %>
		
  </body>
</html>

shcpms/app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p1><%= @content %></p1>
<h2><%= link_to "welcome", '/index', :method => :get %></h2>

shcpms/app/views/patients/patientspage.html.erb
<h1><%= @title %></h1>
<p1><%= @content %></p1>
<h2><%= link_to "About", '/about', :method => :get %></h2>

shcpms/app/views/welcome/index.html.erb
<h1><%= @title %></h1>
<p1><%= @content %></p1>
<h2><%= link_to "About", '/about', :method => :get %></h2>